### ISSUE TITLE
`useFieldInitialValue` with `listField` - Maximum update depth exceeded

### ISSUE THREAD

**Issue by schiller-manuel** [form-atoms/field#104]
I am not sure if this is a bug or just me doing something wrong.

I have the following setup:

```tsx
interface Description {
    id?: string;
    language: string;
}

const descriptionsAtom = listField({
  value: [],
  builder: ({ id, language, context }: Description) => ({
    id: fieldAtom({ value: id }),
    languageCode: textField({ value: language }),
  }),
});

function FormComponent() {
    const apiResult = useSuspenseQuery(/* ... */);
    const initialDescriptions : Description[] = apiResult.data;
    useFieldInitialValue(descriptionsAtom, initialDescriptions);

   /* ... */
}
```

At runtime, when the backend response does not contain the `id` property, the following error occurs:

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

As of v.3.2.3 `useFieldInitialValue` from `form-atoms` has a `areEqual` option. When I log the values that are compared in in this function, I see that one has `id: undefined` and the other (the value from the API) does not have the `id` property at all:

![Screenshot 2024-02-04 at 14 46 17](https://github.com/form-atoms/field/assets/6340397/a081e116-09f3-4c5b-a2a4-93e7f4e2c79e)
![Screenshot 2024-02-04 at 14 47 22](https://github.com/form-atoms/field/assets/6340397/7866ca27-3bb0-472d-9697-38e81a605c78)

This mismatch causes the equality check to fail and thus an infinite loop is entered that causes the above React error.

**Comment by jaredLunde** [comment]
Unfortunately I don't know anything about `listField` as it is not something I personally use. You'd have to file an issue there. But using a custom `areEqual` function should get you out of this problem.

**Comment by schiller-manuel** [comment]
`listField` is from `@form-atoms` which this repo is about, right? or am I wrong here?

**Comment by jaredLunde** [comment]
Sorry missed that this was filed in `field` already

**Comment by MiroslavPetrik** [comment]
@schiller-manuel I think that I need to supply custom `areEqual` function in the hook of listfield as @jaredLunde indicates.
Also there is custom hydrate hook, which will be removed after the PR in `form-atoms` is merged so that might play a role here.

**Comment by MiroslavPetrik** [comment]
The issue happens, because everytime the `listAtom.value` is accessed, the new array is computed from the nested values. So currently, the shallow equal test with the `initialValue` is always false, and so new value is set until it crashes with stack overflow.

Here, I would like to avoid doing `deepEquals` for the values. There is easy fix for this. There is copy of the `listAtom.value` which has initialized atoms from the last init (`initialFormListAtom`). That way we can quickly check if the array changed. This is used to get the `dirty` flag.

We can compare the current formList with the initial, and if they are equal, we can safely return the `initialValue` originally passed to the `useFIV` hook:

```ts
  const valueAtom = atom(
    (get) => {
      const formLists = get(_formListAtom);

      if (arraysShallowEqual(get(initialFormListAtom), formLists)) {
        const maybeInitialValue = get(initialValueAtom);
        if (maybeInitialValue) {
          return maybeInitialValue;
        }
      }

      return formLists.map((formAtom) => {
        const formAtoms = get(formAtom);
        const { fields } = get(formAtoms.values);

        return fields as Value;
      });
    }
)
```
This will stop the infinite updates, but it introduces a limitation, that the `builder` won't be used for the initial items!
E.g. the `id: undefined` which was introduced from the builder, won't be in the submit data, unless you make the `listAtom` dirty.
Maybe somebody would rely on it to generate the `id` on the client there e.g.

```ts
import {v4} from "uuid";

const descriptionsAtom = listField({
  value: [],
  builder: ({ id, language, context }: Description) => ({
    id: fieldAtom({ value: v4() }), // generate ids on the client
    languageCode: textField({ value: language }),
  }),
});
```
But i would say that is ok, as the `initialValue` likely is from the database where items already have `ids`.
So, in the example above, the IDs would be added for newly inserted items in the list... also for the initial... but would be in the submit data, only if you really change the input...
