### ISSUE TITLE
`dirty` flag of `listField` is wrong when initial value is set to current value via `useFieldInitialValue`

### ISSUE THREAD

**Issue by schiller-manuel** [form-atoms/field#105]
**Describe the bug**

In my form, the user shall stay on the form page after form submit.
When the submit button is clicked, the form data is sent to the backend and returns the updated values.
`useFieldInitialValue` is used to update the initial value of all form fields after the updated values are 

This works for e.g. `textField`, but not for `listField`.
When the initial value of a  `listField` is set to the current value via `useFieldInitialValue`, the `dirty` flag of a `listField` is still `true` while it should now be `false`.

**To Reproduce**

I created a reproducer at https://github.com/schiller-manuel/form-atoms-field-bug/blob/main/src/App.tsx
Here the backend request/response communication is replaced by a simple `useState`.

https://github.com/form-atoms/field/assets/6340397/9fa5120a-a03e-4025-a3ef-108b1994b55f

The `Foo` labeled field is a simple `textField`. When its value is changed, the form state switches to `dirty`.
After submit, the form state is not dirty anymore.

The `First Name` labeled field is inside of a `listField`. When its value is changed, the form state switches to `dirty`.
After submit, the form state is STILL dirty.

**Expected behavior**

`dirty` flag of `listField` should be `false` in this case

**versions**
- form-atoms v3.2.3
- @form-atoms/field v4.0.11

**Comment by MiroslavPetrik** [comment]
There is a passing test for this case
https://github.com/form-atoms/field/blob/901fb645236e66054e54f652bc10632e8498f579/src/atoms/list-atom/listAtom.test.ts#L337

Maybe its related to the changes in the `useFieldInitialValue`

**Comment by MiroslavPetrik** [comment]
The thing is that the `set(valueAtom)` is not called, as the `useFIV` calls it only for pristine field:
https://github.com/form-atoms/form-atoms/blob/608e42c7f8f223fe3d36585770ae5a2a6cfb5575/src/index.tsx#L1055
and the listAtom currently cannot return to pristine, once it's dirty.

What needs to be done is to handle the write into `initialValueAtom` of the listAtom, so it will recursively write into the nested inputs. That way, the `dirty` will all return to false, after the submit. 

But this is simplistic and correct only for the case, where we update the already existing items in the list. In case items were reordered, or added/removed, this could potentially mix data on the background.

E.g. we can't assume anything, about how the `initialValue` is obtained, yes in most of our happy scenarios its the new data returned from the BE after the save. But also it could be from initial query, which gets refetched after becoming stale and could return potentially different data updated by another user.

Bad scenario:
1. change items locally
2. go AFK, initial query becomes stale
3. return back, focus browser window
4. query re-fetches, and initialValues are updated in the background
5. a single item could have touched+dirty and untouched fields
6. the untouched fields which got reinitialized could be from a reordered item, now mixed with the touched+dirty inputs of another reordered item

So potentially, the `listAtom` could get `keyField` property as not to merge reordered items. The key would be something like the `id` from your other issue, where you have `languages`.

Other options I thought about:

1. reinitializing manually
E.g. after the successful submit, the form will be reset, so the initial data will behave like fresh render

2. hydrating atoms with the `dangerouslyHydrate` flag.
Like the above, we could use the `useHydrateAtoms` hook with the flag, to force rehydration. The flag would depend solely on the submit status of the update query, e.g. `submitStatus === "success"`. Here we would have to after the rehydration reset the query somehow so it won't rehydrate again... perhaps when any of the fields is changed.

3. Make the `useFIV` behave like the `useSetFieldValue`, so basically, once you change the `initialValue` for the `listAtom,` its `value` would be recalculated. Here you could change the local changes, in case the refetched query (from the scenario above) reinitializes the input.

I like this, as I think that often the `<List />` component is used on a separate page, used often to configure something, value of which is changed rarely, and even less concurrently (multiple users changing the value).

4. change the `dirtyAtom` evaluation?
Perhaps do deepEquals compare instead of watching the nested field's `dirty` state. Not sure how this would work, when the created items are returned from BE with new `ids`...

**Comment by MiroslavPetrik** [comment]
@schiller-manuel I went with the option 3 from "other options" above.
It uses special useFIV hook, that only sets the `valueAtom` which also clears the `dirty` flag.

Solved for me the case, where my submit button returned to disabled state, just after the new initialValue was returned from the server render.

If somebody would use this with the client data fetching, like in `useQuery()` and would face the issue mentioned above, then the initialValue must be deeply compared with the query value as to keep the referential identity.
