### ISSUE TITLE
Docs: Clicking on show code throws empty screen

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/field#119]
**Describe the bug**

**To Reproduce**
1. Go to any story 'https://form-atoms.github.io/field/?path=/docs/fields-booleanfield--docs'
2. Click on 'Show code '
3. Notice the Page is empty and error

**Expected behavior**
I should be able to see sample code to start editing / copy 

**Screenshots**
![Screenshot 2024-03-08 at 3 27 37 PM](https://github.com/form-atoms/field/assets/14316332/3314a206-24d2-4cfa-9a1e-aa171cd48595)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MiroslavPetrik** [comment]
Yeah, thanks for the issue.
I knew about this and you made me look into it more.
I've disabled it as even if it would work, those code samples were not usable, because it was some custom processed code from the storybook example...
Another issue with the storybook code is that it has awful color theme which I cannot configure...

On the other hand, in the `list-atom` repo, I have only custom code examples, and I would like to have those here as well, but that would be lots of work.

once again thanks for the issue, as I made the list-atom examples collapsible, which can be reused here.
https://form-atoms.github.io/list-atom/
