### ISSUE TITLE
how to i18n validation errors?

### ISSUE THREAD

**Issue by schiller-manuel** [form-atoms/field#58]
I use the following approach for i18n of validation errors:
`required_error` is set to  the corresponding translation key.
This translation key is then later translated to the actual text:

```typescript
export const fieldAtom = textField({
  name: 'name',
  required_error: 'form.validationErrors.fieldRequired',
});

import { useTranslation } from 'react-i18next';
import {TextField} from 'some-component-library';
import {
  type TextFieldProps,
  useTextFieldProps,
  useFieldError,
} from '@form-atoms/field';
function FormTextField({field}: TextFieldProps) {
  const props = useTextFieldProps(field);
  const errors = useFieldError(field);
  const { t } = useTranslation();
  return (
    <TextField
      name={props.name}
      value={props.value}
      onBlur={props.onBlur}
      onChange={props.onChange}
      error={t(errors.error)}
    />
}

function SomeView() {
    return <FormTextField field={fieldAtom} /> 
}
```

What are your thoughts about how to use your library with i18n in mind?

**Comment by MiroslavPetrik** [comment]
Hey, you can translate all the zod messages globally with [zod-18n](https://github.com/aiji42/zod-i18n).

For the custom errors, personally, with the `required_error` I would translate at the begining:

```ts
export const fieldAtom = textField({
  name: 'name',
  required_error: t('form.validationErrors.fieldRequired'),
});
```

Because, when consuming the errors, I would expect to have final messages ready to be rendered.

Note that the `required_error` is there just to allow configuring the 'internal schemas' inside of the fields just to not lock you out. You can think of it as PoC so it's open to changes.

**Comment by schiller-manuel** [comment]
Thanks for pointing me at zod-i18n!
Looks like short term solution would be to define my own `textField` atom (based on zodField) then, since I need to modify the zod scheme by adding  something like this: 
`.refine(() => false, { params: { i18n: "form.validationErrors.fieldRequired" } })`

Ideally, I could still use your `textField` and configure it to use zod-i18n somehow 🤔

**Comment by MiroslavPetrik** [comment]
You can pass you custom schema:

```ts
const f = textField({schema: z.string().refine(() => false, { params: { i18n: "form.validationErrors.fieldRequired" } }) })
```
